SonarColud ingetration
BME-MIT-IET/iet-hf-2022-mind1-a-nev pull request #4
Opened 2022-05-15 18:55 UTC by halacska99

#1 try

2022-05-15 19:02 UTC, aront22 requested changes
name: Build helyett lehetne mondjuk name: Build Sonar Cloud Build az action neve

2022-05-15 19:03 UTC, halacska99 commented
> name: Build helyett lehetne mondjuk name: Build Sonar Cloud Build az action neve

Tényleg, el is felejtettem. Köszi, hogy észrevetted!

2022-05-15 19:05 UTC, szabi43 commented
A pull request nevében van 2 typo.

2022-05-15 19:05 UTC, halacska99 commented
> A pull request nevében van 2 typo.

Köszi, javítom!

2022-05-15 19:34 UTC, szabi43 approved these changes
Jónak tűnik

2022-05-15 19:35 UTC, skidov approved these changes
Nekem jónak tűnik

2022-05-15 19:36 UTC, aront22 approved these changes
Így már jó lesz a javított név, sokkal egyértelműbb

2022-05-17 15:28 UTC, halacska99 commented
Megpróbáltam egy másik futtatási módszert a SonarCloud-hoz. Ugyanaz lett az eredmény, szóval visszaállítottam az eredeti fájl, kérlek ellenőrizzétek le. Köszi!

2022-05-18 12:11 UTC, aront22 approved these changes
Jó lesz.

2022-05-18 12:23 UTC, skidov approved these changes
Jónak tűnik

2022-05-19 15:27 UTC, merged